// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false ,
  indexing: [
    {index:1 , name:'الْفَاتِحَة' },
    {index:2 , name:'الْبَقَرَة' },
    {index:50 , name:'آلِ عِمْرَانَ' },
    {index:77 , name:'النِّسَاء' },
    {index:106 , name:'الْمَائِدَة' },
    {index:128 , name:'الْإِنْعَام' },
    {index:151 , name:'الْأَعْرَاف' },
    {index:177 , name:'الْأَنْفَال ' },
    {index:187 , name:'التَّوْبَة' },
    {index:208 , name:'يُونُس ' },
    {index:221 , name:'هُود ' },
    {index:235 , name:'يُوسُف ' },
    {index:249 , name:'الرَّعْد' },
    {index:255 , name:'إِبْرَاهِيم ' },
    {index:262 , name:'الْحِجَر' },
    {index:267 , name:'النَّحْل' },
    {index:282 , name:'الْإِسْرَاء' },
    {index:293 , name:'الْكَهْف' },
    {index:305 , name:'مَرْيَم' },
    {index:312 , name:'طَه ' },
    {index:322 , name:'الْأَنْبِيَاء' },
    {index:332 , name:'الْحَجّ' },
    {index:342 , name:'الْمُؤْمِنُون' },
    {index:350 , name:'النُّور' },
    {index:359 , name:'الْفُرْقَان' },
    {index:367 , name:'الشُّعَرَاء' },
    {index:377 , name:'النَّمْل' },
    {index:385 , name:'الْقَصَص' },
    {index:396 , name:'الْعَنْكَبُوت' },
    {index:404 , name:'الرُّوم' },
    {index:411 , name:'لُقْمَان' },
    {index:415 , name:'السَّجْدَة' },
    {index:418 , name:'الْأَحْزَاب' },
    {index:428 , name:'سَبَأ' },
    {index:434 , name:'فَاطِر' },
    {index:440 , name:'يسٓ' },
    {index:446 , name:'الصّافّات ' },
    {index:453 , name:' صَّ' },
    {index:458 , name:' الزَّمْر' },
    {index:467 , name:'  غَافِرٌ' },
    {index:477 , name:'فُصِلَّت' },
    {index:483 , name:'الشَّوريٓ' },

    {index:489 , name:'الزُّخْرُف' },
    {index:496 , name:'الدُّخَان' },
    {index:499 , name:'الْجَاثِيَة' },
    {index:502 , name:'الأَحْقَاف' },
    {index:507 , name:'مُحَمَّد' },
    {index:511 , name:'الْفَتْح' },
    {index:515 , name:'الْحُجُرَات' },
    {index:518 , name:'قٓ' },
    {index:520 , name:'الذَّارِيَات' },
    {index:523 , name:'الطُّور' },
    {index:526 , name:'النَّجْم' },
    {index:528 , name:'الْقَمَر' },
    {index:531 , name:'الرَّحْمَن' },
    {index:534 , name:'الْوَاقِعَة' },

    {index:537 , name:'الْحَدِيد' },
    {index:542 , name:'الْمُجَادَلَة' },
    {index:545 , name:'الْحَشْر' },
    {index:549 , name:'الْمُمْتَحِنَة' },
    {index:551 , name:'الصَّفّ' },
    {index:553 , name:'الْجُمُعَة' },
    {index:554 , name:'الْمُنَافِقُون' },
    {index:556 , name:'التَّغَابُن' },
    {index:558 , name:'الطَّلَاق' },
    {index:560 , name:'التَّحْرِيم' },
    {index:562 , name:'الْمَلِك' },
    {index:564 , name:'الْقَلَم' },
    {index:566 , name:'الْحَاقُه' },
    {index:568 , name:'الْمَعَارِج' },
    {index:570 , name:'نُوح ' },
    {index:572 , name:'الْجِنّ' },
    {index:574 , name:'الْمُزَّمِّل' },
    {index:575 , name:'الْمُدَّثِّر' },
    {index:577 , name:'الْقِيَامَة' },
    {index:578 , name:'الْإِنْسَان' },
    {index:580 , name:'الْمُرْسَلاَت' },
    {index:582 , name:'النَّبَأ' },
    {index:583 , name:'النَّازِعَات' },
    {index:585 , name:'عَبْس' },
    {index:586 , name:'التَّكْوِير' },
    {index:587 , name:'الانْفِطار' },
    {index:587 , name:'الْمُطَفِّفِين' },
    {index:589 , name:'الِانْشِقَاق' },
    {index:590 , name:'الْبُرُوج' },


    {index:591 , name:'الطَّارِق' },
    {index:591 , name:'الأعلي' },
    {index:592 , name:'الْغَاشِيَة' },
    {index:593 , name:'الْفَجْر' },
    {index:594 , name:'الْبَلَد' },
    {index:595 , name:'الشَّمْس' },
    {index:595 , name:'اللَّيْل' },
    {index:596 , name:'الضٌّحي' },
    {index:596 , name:'الشَّرْح' },
    {index:597 , name:'التِّين' },
    {index:597 , name:'الْعَلَق' },
    {index:598 , name:'الْقَدْر' },
    {index:598 , name:'الْبَيِّنَة' },
    {index:599 , name:'الزّلْزَلَة' },
    {index:599 , name:'الْعَادِيَّات' },
    {index:600 , name:'الْقَارِعَة' },
    {index:600 , name:'التَّكَاثُر' },
    {index:601 , name:'الْعَصْر' },
    {index:601 , name:'الْهَمْزَة' },
    {index:601 , name:'الْفِيل' },
    {index:602 , name:'قُرَيْش' },
    {index:602 , name:'الْمَاعُون' },
    {index:602 , name:'الْكَوْثَر' },
    {index:603 , name:'الْكَافِرُون' },
    {index:603 , name:'النَّصْر' },
    {index:603 , name:'المسَد' },
    {index:604 , name:'الْإِخْلَاص' },
    {index:604 , name:'الْفَلَق' },
    {index:604 , name:'النَّاس' },
    ]
};


/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
